import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h2>Home Page for material ui branch</h2>
    </Layout>
  );
}
