import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.scss";
import Container from "@mui/material/Container";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Container className={styles.container}>
        <h2>Home Page for material ui branch</h2>
      </Container>
    </Layout>
  );
}
